# Site settings
title: binary.phile
description: >-
  Musings, mostly on technology.
url: "https://binaryphile.github.io"

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/

minima:
  social_links:
    - platform: github
      user_url: https://github.com/binaryphile
    - platform: keybase
      user_url: https://keybase.io/binaryphile
    - platform: mastodon
      user_url: https://cryptodon.lol/@binaryphile
