# Site settings
title: binary.phile
description: >-
  Musings, mostly on technology.
url: "https://binaryphile.github.io"
github_username:  binaryphile

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
