# Site settings
title: binary.phile
description: >-
  Musings, mostly on technology.
url: "https://binaryphile.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  binaryphile

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
